### ISSUE TITLE
MAC address 

### ISSUE THREAD

**Issue by RCdiy** [onceLabs/BLE-Hero#11]
Could you please add display of the address?

**Comment by JoeBakalor** [comment]
Hi @RCdiy, unfortunately on iOS we do not have access to the MAC address in the advertisement data like on Android. Are you developing the firmware for the device you are trying to connect to? If you want access to the MAC address on iOS, you can add it in the manufacturer data in the advertisement packet. What is your need for the MAC address? Maybe we can provide an alternative solution.

**Comment by RCdiy** [comment]
Thank you:)
I’m going to use a Raspberry Pi to open a garage door when the iBeacon of a Tesla is detected. On the Pi I get the address as the unique identifier. 

I guess I could use the uuid instead. But this app does not show it?

The app shows the name but the python code I’m using does not. 

{'type': 'iBeacon', 'uuid': '74278bda-b644-4520-8f0c-720eaf059935', 'major': 0, 'minor': 41829, 'rssi': -63, 'macAddress': '84:ee:03:ed:ea:1b'}

Anyway this is not related to your app. I was just looking for a way to have people scan the information using their phone instead of running a python script or me having to write an easy to use python tool. 

Rav

Have an awesome day!

Ravi Gupta, PMP
Founder of Hike For Happiness
A Mental Health Fundraiser
http://hikeforhappiness.ca/
(519) 697-0796

**Comment by JoeBakalor** [comment]
@RCdiy On iOS, apple hides iBeacons unless we register the UUID with CoreLocation.  I don't know why they do that, I'm sure they have a good reason, but it's a pain for development.  If you download an iBeacon dev app from the App Store, you can register the UUID and it should show up.  We wanted to add public support for iBeacons in the app but it's not very intuitive in our context so we have not made that feature public yet.  We can give you access to the feature if you'd like to test it.  Send us an email at support@oncelabs.com if you are interested
